services:
  - 
    name: Weighted Round Robin Service
    matcher: /
    strategy: WeightedRoundRobin
    replicas:
      - url: http://localhost:8081
        metadata:
          weight: 10
      - url: http://localhost:8082
        metadata:
          weight: 5
